// <auto-generated />
namespace CA2_S00158056.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class actorDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actorDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201411241459596_actorDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
